// Response
const HTTP_OK = 200; 
const HTTP_UNAUTHORIZED = 401;
const HTTP_FORBIDDEN = 403;
const HTTP_NOT_FOUNT = 404;
const HTTP_CONFLICT = 409;
const HTTP_INTERNAL_SERVER_ERROR = 500;

// Messages
const MESSAGE_SUCCESS = "Success";
const MESSAGE_REGISTER_SUCCESS = "Usuário foi autenticado com sucesso!";
const MESSAGE_LOGIN_SUCCESS = "Usuário logado com sucesso!";
const MESSAGE_REGISTER_PENDING = "Usuário salvo! Aguardando confirmação  por email!";
const MESSAGE_REGISTER_CONFLICT = "Usuário já cadastrado na base de dados!";
const MESSAGE_CONFIRMATION_FAILED = "Usuário não encontrado!";
const MESSAGE_INTERNAL_ERROR = "Erro interno no servidor!";
const MESSAGE_NOT_AUTHENTICATED = "Usuário não autenticado!";
const MESSAGE_WRONG_EMAIL_PASS = "Email e/ou senha incorreto(s)!";
const MESSAGE_NOT_AUTHORIZED = "Usuário não autorizado!";
const MESSAGE_NOT_FOUND = "Não encontrado!";

module.exports = {
    HTTP_OK:                     HTTP_OK,
    HTTP_UNAUTHORIZED:           HTTP_UNAUTHORIZED,
    HTTP_FORBIDDEN:              HTTP_FORBIDDEN,
    HTTP_NOT_FOUNT:              HTTP_NOT_FOUNT,
    HTTP_CONFLICT:               HTTP_CONFLICT,
    HTTP_INTERNAL_SERVER_ERROR:  HTTP_INTERNAL_SERVER_ERROR,
    MESSAGE_SUCCESS:             MESSAGE_SUCCESS,
    MESSAGE_REGISTER_SUCCESS:    MESSAGE_REGISTER_SUCCESS,
    MESSAGE_LOGIN_SUCCESS:       MESSAGE_LOGIN_SUCCESS,
    MESSAGE_REGISTER_PENDING:    MESSAGE_REGISTER_PENDING,
    MESSAGE_REGISTER_CONFLICT:   MESSAGE_REGISTER_CONFLICT,
    MESSAGE_CONFIRMATION_FAILED: MESSAGE_CONFIRMATION_FAILED,
    MESSAGE_INTERNAL_ERROR:      MESSAGE_INTERNAL_ERROR,
    MESSAGE_NOT_AUTHENTICATED:   MESSAGE_NOT_AUTHENTICATED,
    MESSAGE_WRONG_EMAIL_PASS:    MESSAGE_WRONG_EMAIL_PASS,
    MESSAGE_NOT_AUTHORIZED:      MESSAGE_NOT_AUTHORIZED,
    MESSAGE_NOT_FOUND:           MESSAGE_NOT_FOUND
}